const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{текст1: 0},
	{играть: 0},
	{текст2: 0},
	{ТайловыйФон2: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{чебурашка: 0},
	{ТайловыйФон3: 0},
	{Текст: 0},
	{победа: 0},
	{Твёрдый: 0},
	{платформа: 0},
	{ТайловыйФон4: 0},
	{Спрайт: 0},
	{Текст3: 0},
	{гена: 0},
	{ТайловыйФон5: 0},
	{Текст4: 0},
	{меню2: 0},
	{Текст5: 0},
	{ТайловыйФон6: 0},
	{СтарухаШапокляк: 0},
	{Пуля: 0},
	{бои: 0},
	{ТайловыйФон7: 0},
	{инструкция: 0},
	{Текст7: 0},
	{Текст8: 0},
	{Текст6: 0},
	{кнопкаИнструкция: 0},
	{меню: 0},
	{ТайловыйФон8: 0},
	{Текст9: 0},
	{ТайловыйФон9: 0},
	{Текст10: 0},
	{гена2: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Текст11: 0},
	{ТайловыйФон10: 0},
	{ТайловыйФон11: 0},
	{ТайловыйФон12: 0},
	{Спрайт4: 0},
	{бревна: 0},
	{Текст12: 0},
	{Текст13: 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	текст1: class extends self.ITextInstance {},
	играть: class extends self.IButtonInstance {},
	текст2: class extends self.ITextInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	чебурашка: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Текст: class extends self.ITextInstance {},
	победа: class extends self.IButtonInstance {},
	платформа: class extends self.ISpriteInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	гена: class extends self.ISpriteInstance {},
	ТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	Текст4: class extends self.ITextInstance {},
	меню2: class extends self.IButtonInstance {},
	Текст5: class extends self.ITextInstance {},
	ТайловыйФон6: class extends self.ITiledBackgroundInstance {},
	СтарухаШапокляк: class extends self.ISpriteInstance {},
	бои: class extends self.ISpriteInstance {},
	ТайловыйФон7: class extends self.ITiledBackgroundInstance {},
	инструкция: class extends self.ITextInstance {},
	Текст7: class extends self.ITextInstance {},
	Текст8: class extends self.ITextInstance {},
	Текст6: class extends self.ITextInstance {},
	кнопкаИнструкция: class extends self.IButtonInstance {},
	меню: class extends self.IButtonInstance {},
	ТайловыйФон8: class extends self.ITiledBackgroundInstance {},
	Текст9: class extends self.ITextInstance {},
	ТайловыйФон9: class extends self.ITiledBackgroundInstance {},
	Текст10: class extends self.ITextInstance {},
	гена2: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Текст11: class extends self.ITextInstance {},
	ТайловыйФон10: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон11: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон12: class extends self.ITiledBackgroundInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	бревна: class extends self.ISpriteInstance {},
	Текст12: class extends self.ITextInstance {},
	Текст13: class extends self.ITextInstance {}
}